using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Rock_Solid
{
	class Back
	{
		public static Int32 BACK_ID = 0;

		public static string BACK_PULLEYCOSTAS = "0";
		public static string BACK_PULLEYFRENTE = "0";
		public static string BACK_PULLEYINVERTIDO = "0";
		public static string BACK_REMADAHORIZONTAL = "0";
		public static string BACK_REMADAALTERNADA = "0";
		public static string BACK_REMADACAVALINHO = "0";
		public static string BACK_PUXADORARTICULADO = "0";
		public static string BACK_PECKDECK = "0";
		public static string BACK_PULLOVER = "0";
		public static string BACK_BARRAFIXA = "0";
		public static string BACK_VOADORINVERSO = "0";

		public static Int32 BACK_PULLEYCOSTAS_SERIE = 0;
		public static Int32 BACK_PULLEYFRENTE_SERIE = 0;
		public static Int32 BACK_PULLEYINVERTIDO_SERIE = 0;
		public static Int32 BACK_REMADAHORIZONTAL_SERIE = 0;
		public static Int32 BACK_REMADAALTERNADA_SERIE = 0;
		public static Int32 BACK_REMADACAVALINHO_SERIE = 0;
		public static Int32 BACK_PUXADORARTICULADO_SERIE = 0;
		public static Int32 BACK_PECKDECK_SERIE = 0;
		public static Int32 BACK_PULLOVER_SERIE = 0;
		public static Int32 BACK_BARRAFIXA_SERIE = 0;
		public static Int32 BACK_VOADORINVERSO_SERIE = 0;

		public static Int32 BACK_PULLEYCOSTAS_REP = 0;
		public static Int32 BACK_PULLEYFRENTE_REP = 0;
		public static Int32 BACK_PULLEYINVERTIDO_REP = 0;
		public static Int32 BACK_REMADAHORIZONTAL_REP = 0;
		public static Int32 BACK_REMADAALTERNADA_REP = 0;
		public static Int32 BACK_REMADACAVALINHO_REP = 0;
		public static Int32 BACK_PUXADORARTICULADO_REP = 0;
		public static Int32 BACK_PECKDECK_REP = 0;
		public static Int32 BACK_PULLOVER_REP = 0;
		public static Int32 BACK_BARRAFIXA_REP = 0;
		public static Int32 BACK_VOADORINVERSO_REP = 0;

		public static Int32 BACK_PULLEYCOSTAS_CARGA = 0;
		public static Int32 BACK_PULLEYFRENTE_CARGA = 0;
		public static Int32 BACK_PULLEYINVERTIDO_CARGA = 0;
		public static Int32 BACK_REMADAHORIZONTAL_CARGA = 0;
		public static Int32 BACK_REMADAALTERNADA_CARGA = 0;
		public static Int32 BACK_REMADACAVALINHO_CARGA = 0;
		public static Int32 BACK_PUXADORARTICULADO_CARGA = 0;
		public static Int32 BACK_PECKDECK_CARGA = 0;
		public static Int32 BACK_PULLOVER_CARGA = 0;
		public static Int32 BACK_BARRAFIXA_CARGA = 0;
		public static Int32 BACK_VOADORINVERSO_CARGA = 0;

		public static Int32 BACK_WORKOUT = 0;


		public static void Clear()
		{
			BACK_PULLEYCOSTAS = "";
			BACK_PULLEYFRENTE = "";
			BACK_PULLEYINVERTIDO = "";
			BACK_REMADAHORIZONTAL = "";
			BACK_REMADAALTERNADA = "";
			BACK_REMADACAVALINHO = "";
			BACK_PUXADORARTICULADO = "";
			BACK_PECKDECK = "";
			BACK_PULLOVER = "";
			BACK_BARRAFIXA = "";
			BACK_VOADORINVERSO = "";

			BACK_PULLEYCOSTAS_SERIE = 0;
			BACK_PULLEYFRENTE_SERIE = 0;
			BACK_PULLEYINVERTIDO_SERIE = 0;
			BACK_REMADAHORIZONTAL_SERIE = 0;
			BACK_REMADAALTERNADA_SERIE = 0;
			BACK_REMADACAVALINHO_SERIE = 0;
			BACK_PUXADORARTICULADO_SERIE = 0;
			BACK_PECKDECK_SERIE = 0;
			BACK_PULLOVER_SERIE = 0;
			BACK_BARRAFIXA_SERIE = 0;
			BACK_VOADORINVERSO_SERIE = 0;

			BACK_PULLEYCOSTAS_REP = 0;
			BACK_PULLEYFRENTE_REP = 0;
			BACK_PULLEYINVERTIDO_REP = 0;
			BACK_REMADAHORIZONTAL_REP = 0;
			BACK_REMADAALTERNADA_REP = 0;
			BACK_REMADACAVALINHO_REP = 0;
			BACK_PUXADORARTICULADO_REP = 0;
			BACK_PECKDECK_REP = 0;
			BACK_PULLOVER_REP = 0;
			BACK_BARRAFIXA_REP = 0;
			BACK_VOADORINVERSO_REP = 0;

			BACK_PULLEYCOSTAS_CARGA = 0;
			BACK_PULLEYFRENTE_CARGA = 0;
			BACK_PULLEYINVERTIDO_CARGA = 0;
			BACK_REMADAHORIZONTAL_CARGA = 0;
			BACK_REMADAALTERNADA_CARGA = 0;
			BACK_REMADACAVALINHO_CARGA = 0;
			BACK_PUXADORARTICULADO_CARGA = 0;
			BACK_PECKDECK_CARGA = 0;
			BACK_PULLOVER_CARGA = 0;
			BACK_BARRAFIXA_CARGA = 0;
			BACK_VOADORINVERSO_CARGA = 0;
		}
	}
}
