using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Rock_Solid
{
	class Biceps
	{
		public static Int32 BICEPS_ID = 0;

		public static string BICEPS_ROSCADIRETA = "0";
		public static string BICEPS_ROSCAALTERNADA = "0";
		public static string BICEPS_ROSCAMARTELO = "0";
		public static string BICEPS_ROSCACONCENTRADA = "0";
		public static string BICEPS_ROSCAARTICULADA = "0";
		public static string BICEPS_ROSCABILATERAL = "0";
		public static string BICEPS_ROSCAROLDANA = "0";
		public static string BICEPS_ROSCASIMULTANEA = "0";

		public static Int32 BICEPS_ROSCADIRETA_SERIE = 0;
		public static Int32 BICEPS_ROSCAALTERNADA_SERIE = 0;
		public static Int32 BICEPS_ROSCAMARTELO_SERIE = 0;
		public static Int32 BICEPS_ROSCACONCENTRADA_SERIE = 0;
		public static Int32 BICEPS_ROSCAARTICULADA_SERIE = 0;
		public static Int32 BICEPS_ROSCABILATERAL_SERIE = 0;
		public static Int32 BICEPS_ROSCAROLDANA_SERIE = 0;
		public static Int32 BICEPS_ROSCASIMULTANEA_SERIE = 0;

		public static Int32 BICEPS_ROSCADIRETA_REP = 0;
		public static Int32 BICEPS_ROSCAALTERNADA_REP = 0;
		public static Int32 BICEPS_ROSCAMARTELO_REP = 0;
		public static Int32 BICEPS_ROSCACONCENTRADA_REP = 0;
		public static Int32 BICEPS_ROSCAARTICULADA_REP = 0;
		public static Int32 BICEPS_ROSCABILATERAL_REP = 0;
		public static Int32 BICEPS_ROSCAROLDANA_REP = 0;
		public static Int32 BICEPS_ROSCASIMULTANEA_REP = 0;

		public static Int32 BICEPS_ROSCADIRETA_CARGA = 0;
		public static Int32 BICEPS_ROSCAALTERNADA_CARGA = 0;
		public static Int32 BICEPS_ROSCAMARTELO_CARGA = 0;
		public static Int32 BICEPS_ROSCACONCENTRADA_CARGA = 0;
		public static Int32 BICEPS_ROSCAARTICULADA_CARGA = 0;
		public static Int32 BICEPS_ROSCABILATERAL_CARGA = 0;
		public static Int32 BICEPS_ROSCAROLDANA_CARGA = 0;
		public static Int32 BICEPS_ROSCASIMULTANEA_CARGA = 0;

		public static Int32 BICEPS_WORKOUT = 0;


		public static void Clear()
		{
			BICEPS_ROSCADIRETA = "";
			BICEPS_ROSCAALTERNADA = "";
			BICEPS_ROSCAMARTELO = "";
			BICEPS_ROSCACONCENTRADA = "";
			BICEPS_ROSCAARTICULADA = "";
			BICEPS_ROSCABILATERAL = "";
			BICEPS_ROSCAROLDANA = "";
			BICEPS_ROSCASIMULTANEA = "";

			BICEPS_ROSCADIRETA_SERIE = 0;
			BICEPS_ROSCAALTERNADA_SERIE = 0;
			BICEPS_ROSCAMARTELO_SERIE = 0;
			BICEPS_ROSCACONCENTRADA_SERIE = 0;
			BICEPS_ROSCAARTICULADA_SERIE = 0;
			BICEPS_ROSCABILATERAL_SERIE = 0;
			BICEPS_ROSCAROLDANA_SERIE = 0;
			BICEPS_ROSCASIMULTANEA_SERIE = 0;

			BICEPS_ROSCADIRETA_REP = 0;
			BICEPS_ROSCAALTERNADA_REP = 0;
			BICEPS_ROSCAMARTELO_REP = 0;
			BICEPS_ROSCACONCENTRADA_REP = 0;
			BICEPS_ROSCAARTICULADA_REP = 0;
			BICEPS_ROSCABILATERAL_REP = 0;
			BICEPS_ROSCAROLDANA_REP = 0;
			BICEPS_ROSCASIMULTANEA_REP = 0;

			BICEPS_ROSCADIRETA_CARGA = 0;
			BICEPS_ROSCAALTERNADA_CARGA = 0;
			BICEPS_ROSCAMARTELO_CARGA = 0;
			BICEPS_ROSCACONCENTRADA_CARGA = 0;
			BICEPS_ROSCAARTICULADA_CARGA = 0;
			BICEPS_ROSCABILATERAL_CARGA = 0;
			BICEPS_ROSCAROLDANA_CARGA = 0;
			BICEPS_ROSCASIMULTANEA_CARGA = 0;
		}
	}
}
